### ISSUE TITLE
#421 NR Stats Not Calculating Correctly

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#28]
![sagacity-bad-stats](https://user-images.githubusercontent.com/42775175/45767932-c10df100-bbf8-11e8-844b-825bfedd5806.png)
Checking out the statistics page, it has some erroneous NR stats. We need to review how they are calculated. In the attached image, the Windows 7 hosts are 125% not reviewed. The max should be 100%.

You have O, NF, NA adding up to 100%, which is correct (count divided by total number of assessed PDIs = O + NF + NA). Not Reviewed should be count of NR divided by total PDIs in applicable STIGs (or easier would be divided by total findings)

**Comment by godsgood33** [comment]
Should be fixed with the change to how the counts are being calculated.

**Comment by JeffOdegard** [comment]
Looks good.  Thanks!
