### ISSUE TITLE
#233 Create blank eChecklists from Catalog Management

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#33]
A nice feature would be to export a blank eChecklist for a specific checklist (probably purely manual) with n host columns. A good place for this might be on the Catalog Management Page. The current method requires you to create a category and add your hosts to it, assigning the desired STIGs. It's a little clunky if you don't have scan data, and sometimes you just want a blank eChecklist to work with.

**Comment by godsgood33** [comment]
Published a fix for this.

**Comment by JeffOdegard** [comment]
Nice!  Thank you.
