### ISSUE TITLE
#228 ste_export_import.php Errors

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#34]
The ability to export and import ST&E's is becoming more important as we do more tests and wipe out the database before the next test.  We've had to recreate the ST&E to make changes/additions and/or re-export .ckl files or eChecklists.

Notice: Undefined index: notes in C:\xampp\www\data\ste_export_import.php on line 265

Notice: Undefined offset: 0 in C:\xampp\www\data\ste_export_import.php on line 271

Fatal error: Uncaught Error: Call to a member function get_ID() on null in C:\xampp\www\inc\database.inc:3979 Stack trace: #0 C:\xampp\www\data\ste_export_import.php(272): db->get_Finding(NULL, Object(stig)) #1 C:\xampp\www\data\ste_export_import.php(43): export_STE() #2 {main} thrown in C:\xampp\www\inc\database.inc on line 3979

**Comment by JeffOdegard** [comment]
The ST&E Exported without errors, and there's a lot of data in the file.  I saw that the script has a --import flag.  How do you import an ST&E?  I couldn't find an interface for it.

**Comment by godsgood33** [comment]
The import functionality has not been implemented yet.  The idea would be you run the command `php /data/ste_export_import.php -f='{file}' --import` to import the data.  We can make this a high priority for the next release so that you can import the data if you want.

**Comment by JeffOdegard** [comment]
On my next install I will attempt to import at the command line and let you
know what I find.

**Comment by JeffOdegard** [comment]
This is a future enhancement.  We should just hide the button in 1.3.4.

**Comment by JeffOdegard** [comment]
You already did it - I can't find an import button, so this moves to 1.4
