### ISSUE TITLE
update_db.php switch from STIG library to a-z listing for download

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#50]
Use the A-Z listing page as the default for the STIG downloads (like we do it for the sunset STIGs), and always include the sunset STIGs when downloading the STIGS.  Fall back to the STIG library if it fails.

The trick on this one may be that it's broken into two pages, and it's actually a sub-page that you need to parse to get the actual file links.

**Comment by godsgood33** [comment]
This was actually much easier than it looks.

**Comment by godsgood33** [comment]
Since all the code was already there, I just had to reorganize it a little and it was really easy to do.

**Comment by godsgood33** [comment]
DISA seems to have stuff in place to prevent directly navigating to the pages.  While I can programmatically create a link to the second page, it doesn't work for some reason.  I don't know if they have security stuff in place that prevents it, or if there is something done in JavaScript that allows it to navigate to the second page.  I did try following the logic a little, but couldn't get very far into it.  So I can download the first page file, but then getting to the second page is the problem.

**Comment by godsgood33** [comment]
Reverted this to the previous compilation zip file because I could not get this to work reliably.  Can try again in the future.  I emailed NIST and they indicate their NCP list is accurate.  So I think one way we can go is to download that list then crawl it to download the files directly from DISA.  Will have to attempt that in the future.  Will try to implement by the end of the month in time for the 1.3.4 release.

**Comment by godsgood33** [comment]
Been playing around with the NCP feed...one cool thing is that it includes the sunset list, so it could be a one-stop-shop.  Almost 300 downloads to get all of the zip files.  It took about 20 mins to download them all.  Still have a little bit more to do, but this is a big step!

**Comment by godsgood33** [comment]
I'm closing this for now as this functionality is folded into the Custom Update Server bug #68.
