### ISSUE TITLE
Ops Page slow category load - db->get_Finding_Count_By_Status

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#57]
The Ops page overall loads quickly, until it gets to a category with a lot of hosts (like the 20-30 Win 10 SCC targets).  The attached ste_index_php cachegrind files show that get_Finding_Count_By_Status is taking an inordinate amount of time.
[cachegrind.out.zip](https://github.com/cyberperspectives/sagacity/files/2484482/cachegrind.out.zip)

**Comment by JeffOdegard** [comment]
Here is my slow_log that may have some insights.
[slow_log.zip](https://github.com/cyberperspectives/sagacity/files/2484497/slow_log.zip)

**Comment by godsgood33** [comment]
You think QCacheGrind is good...WinCacheGrind is better...
You can see the actually milliseconds and line number for the function call and know exactly which one is being problematic.  I've got a fix coming here shortly...
![image](https://user-images.githubusercontent.com/1922710/47106161-e7cd4080-d213-11e8-8198-97df738da398.png)

**Comment by JeffOdegard** [comment]
Looks like it's fixed.  Thanks!
