### ISSUE TITLE
SCC Results (Windows/Internet Explorer) not coming out in eChecklist

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#62]
If you import the JOAB SCC results for Windows 10 and IE 11, and then recategorize and export the eChecklist, the Windows tab and Internet Explorer tabs are empty (Win 10) or have just one host populated (IE11).  I did the export after importing 20 hosts.  The other tabs are populated correctly.

I tried again with just one host, importing just Win10 and IE11.  Same result.  The eChecklist is attached.

[Win_10_-_x64-eChecklist-1 (3).xlsx](https://github.com/cyberperspectives/sagacity/files/2520207/Win_10_-_x64-eChecklist-1.3.xlsx)

**Comment by godsgood33** [comment]
Ok...looking in to this, but it looks like SCC changed such that they added a "Id" and "id" attributes to the <Group> tag.  And...now the VMS ID is coming out "xccdf_mil.disa.stig_group_V-63319".  So if you look in your sagacity.golddisk table you should see entries where vms_id = 'xccdf_mil.disa.stig_'  Run the SQL command below to remove those.  I've updated the SCC parser to only grab the V-[\d] value.

`DELETE FROM sagacity.golddisk WHERE vms_id LIKE 'xccdf%'`

**Comment by JeffOdegard** [comment]
So this means we have two bugs.

1. When you add a new checklist to a host, and it adds the associated findings, it doesn't necessarily check to see if the PDIs are already associated.  (But it never mattered, because the other findings come first in the table and are used instead)

2. When you add the new checklists due to OS, you need to reload the exiting PDIs for that host so you can update them with the new findings.

**Comment by JeffOdegard** [comment]
The fix for commenting out the last Insert in post_processing worked when it added a checklist to the host, but it also uncovered a new bug, where the tool never updates - only adds new findings.  I've chased it back as far as database.inc's get_target().  Researching there.
