### ISSUE TITLE
eChecklists - no field validation

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#66]
The exported eChecklists do not have any validation on the status columns.  It must have been removed in your latest updates.

I preferred the drop downs, but your latest validation solution is also acceptable.

![image](https://user-images.githubusercontent.com/42775175/48109234-d0c2b280-e203-11e8-9b56-bfb1c05f4d62.png)

**Comment by godsgood33** [comment]
I assure you, that was not the case when I tested it. There was a drop down. I'll have to investigate further tomorrow.

**Comment by JeffOdegard** [comment]
There was no drop down.  You swapped that out for a more robust validation that took care of the case sensitivity not too long ago.   No worries!  I'll wait until Thursday to install.

**Comment by JeffOdegard** [comment]
Fixed in release 60.
