### ISSUE TITLE
Class 'Logger' not found in helper.inc

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#7]
Attempting to export an eChecklist

[05-Sep-2018 10:41:07 America/Denver] PHP Fatal error:  Uncaught Error: Class 'Logger' not found in C:\xampp\www\inc\helper.inc:848
Stack trace:
#0 C:\xampp\www\ste\export.php(54): convert_log_level()
#1 {main}
  thrown in C:\xampp\www\inc\helper.inc on line 848

**Comment by JeffOdegard** [comment]
Same error pops up when I try to import an eChecklist.  (Same function is called.)

**Comment by cyberperspectives** [comment]
Fixed
