### ISSUE TITLE
No eChecklist icon after import

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#70]
When importing eChecklist results, the eChecklist icon doesn't always appear on the ST&E Ops page.  We verified that the eChecklist had the right host names, and the data is in the database.  (Matt exported another eChecklist and verified everything was correct.)

The icon is necessary because that is how we track what files have been imported for certain hosts to make sure that we've received all of our scan and test data before exporting the final .ckl files at the end of the test.

**Comment by godsgood33** [comment]
Try to duplicate this on an unclass system and get a screenshot of the ops page.  Then look at the target details and see if the checklist is assigned to the target.  If it's not assigned, then it's not going to appear (which would put those findings in the orphan tab).

**Comment by JeffOdegard** [comment]
Seems to be working now.
