### ISSUE TITLE
Install doesn't automatically download and install database

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#72]
On a normal install, Sagacity doesn't automatically download and install updates.  Not sure if this should be looked at or if the new download functionality should be implemented, but it needs to work for release.

**Comment by godsgood33** [comment]
Just tested it on Win with a fresh install and it worked just fine.  I might need to disable the "Next" button until the AJAX returns successful from the first page change.

**Comment by JeffOdegard** [comment]
Fixed!
