### ISSUE TITLE
Import eChecklist - occasional findings flipped to Not Reviewed

### ISSUE THREAD

**Issue by JeffOdegard** [cyberperspectives/sagacity#80]
This is one we've been trying to chase down and reproduce, but haven't been able to.  It's occurring on different checklists from different assessments.

Occasionally, when we import an eChecklist with no pre-existing hosts in the database, a finding will change from Open, Not a Finding or Not Applicable to Not Reviewed.  We can repeat this with the same checklist on different Sagacity installs on different laptops, but can't find any differences between the same echecklists on different systems.  (E.g. McAfee AV Local Client checklist from two different systems - same basic findings:  one flips the findings (DTAM162, DTAM163), and the other doesn't).  We have seen this happen on Windows 10, Solaris 11, VMware, vCenter, and McAfee - and only one or two findings per checklist.

If I modify the finding status on the checklist back to Not A Finding and re-import the spreadsheet, it gets changed to what it's supposed to be, so I wonder if it's when you first import the host and assign the findings that it's getting flipped.

I have tried to recreate the problem using test data, but so far haven't been able to.  I'll continue to try, but maybe we can look at the code that creates a host, then creates a finding when eChecklists are first imported.

**Comment by godsgood33** [comment]
"Occasionally, when we import an eChecklist with no pre-existing hosts in the database, a finding will change from Open, Not a Finding or Not Applicable to Not Reviewed."
This statement really confuses me.  If there are "no pre-existing hosts in the database" how does a finding flip?  Are you saying that it goes from O, NF, NA in the checklist to NR in the database?  If that is the case, then it is probably a bug in defaulting the status or in deconflicting the different statuses.  Do you have an example file this happens with?

**Comment by JeffOdegard** [comment]
So the finding in the originally checklist is set to open, not applicable,
not a finding, and in the database it gets changed to not reviewed

**Comment by godsgood33** [comment]
I think I may have figured out what some of the problem is.  For a test, export an empty checklist from the Catalog Management page.  For the McAfee, for example, there are 117 findings that show in the file, but there are only 87 findings associated with that checklist, so there are 30 STIGs that are duplicated in this checklist.

**Comment by JeffOdegard** [comment]
Those are the ones that have two V IDs in the golddisk table.  They
actually go with the managed checklist

**Comment by JeffOdegard** [comment]
So the fix I think would be to, when parsing, 1. explicitly look for a status that looks like a formula (containing "="), 2. set the status to Not Reviewed and then 3. create an error message like Matt describes - with an error icon on the results page (just like the Nessus failed authentication message) with a message "Formula found in Status column."  4. You could also append that text to the Notes for that finding to make it easier to find.

**Comment by godsgood33** [comment]
I added a line to lock the cells from A11:E(last row).  You have to put a password when locking the cells, so I just put "sagacity".

Also, add an explicit check that the status is one of 7 expected values.  If not, do what you request.

**Comment by JeffOdegard** [comment]
I tested this using =F18 (or another valid cell).  It properly set it to Not Reviewed, and added a note, but the note was repeated 3 times (I only changed one hosts statuses)

The Note looked like:
Formula found in status columnFormula found in status column
Formula found in status column

It should be stated once.

Also, could we get a warning on the Results page for the scan (exclamation point icon and text saying "Formula found in status column" ?

**Comment by godsgood33** [comment]
It's supposed to be doing that already.

**Comment by godsgood33** [comment]
Ok, so the import code is working as designed and how it should work.  The problem is on export.  It concatenates all the note values into one column, so thus it's duplicated 3 times.  This is a symptom of the design flaw in the notes and targets.  To long-term fix this we need to split the notes and design a better way of displaying them.  Maybe we need to create an "Analyst Notes" worksheet that has STIG ID, Target, Note?

I changed one thing on eChecklist export and that seemed to help a lot!  Let me know what you see.

**Comment by cyberperspectives** [comment]
Commit coming...
![image](https://user-images.githubusercontent.com/28206885/51206207-892c6700-18d5-11e9-8b5f-dc986af6f069.png)

**Comment by JeffOdegard** [comment]
Fixed!  Release it!
