### ISSUE TITLE
Missing destination for xdebug file copy in install.bat

### ISSUE THREAD

**Issue by mshuter** [cyberperspectives/sagacity#82]
Install .bat line 63 reads:

copy c:\xampp\www\conf\php_xdebug-2.6.0-7.2-vc15.dll 

Should read: 

copy c:\xampp\www\conf\php_xdebug-2.6.0-7.2-vc15.dll C:\xampp\php\ext\php_xdebug-2.6.1-7.2-vc15.dll

**Comment by mshuter** [comment]
Also just realized php-dev.ini points to php_xdebug-2.6.1-7.2-vc15.dll but the version of xdebug included in conf is php_xdebug-2.6.0-7.2-vc15.dll.

**Comment by godsgood33** [comment]
Committing a fix

**Comment by JeffOdegard** [comment]
This is fixed.
